value = input("Digite algo:")

print("O tipo prmitivo é:", type(value))
print("Só tem espaços?", value.isspace())
print("É um número:", value.isnumeric())
print("É alfabético:", value.isalpha())
print("É alfanumérico:", value.isalnum())
print("Está em maiúculo:", value.isupper())
print("Está em minúsculo:", value.islower())
print("Está capitalizada:", value.istitle())
print("É um dígito:", value.isdigit())
print("È um identificador:", value.isidentifier())
print("È um printável:", value.isprintable())